language: objective-c

before_install:
  - git submodule update --init

rvm:
  - "system; export CEDAR_SDK_VERSION=7.1 #"

env:
  matrix:
    - CEDAR_SDK_RUNTIME_VERSION="6.0"
    - CEDAR_SDK_RUNTIME_VERSION="6.1"
    - CEDAR_SDK_RUNTIME_VERSION="7.0"
    - CEDAR_SDK_RUNTIME_VERSION="7.1"

script: rake
